### ISSUE TITLE
Webdriver-manager 12.0.4 stops with Unhandled 'error' event

### ISSUE THREAD

**Issue by powercycle** [angular/webdriver-manager#218]
webdriver-manager: using global installed version 12.0.2
[10:30:53] I/file_manager - creating folder H:\git\devops-cell\node_modules\prot
ractor\node_modules\webdriver-manager\selenium
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 192.30.253.116:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

**Comment by cnishina** [comment]
Needs more information. What were you doing? What command are you sending? Do you have a proxy? etc.

**Comment by powercycle** [comment]
Issuing 'webdriver-manager update' command.

I do have a proxy, however, setting it creates the same result.

Any way to get the system to provide more data?

**Comment by cnishina** [comment]
Proxy flags are not being sent down. Should be fixed with #208 (originally reported with #207). This has been fixed and is awaiting release. Will leave this issue open to prevent dups.

**Comment by powercycle** [comment]
so I will do a:
npm install -g webdriver-manager to fix this when it gets released, correct?

**Comment by cnishina** [comment]
Yes. I believe that would fix it. I hope to get around to a release some time this week.

**Comment by cnishina** [comment]
Released 12.0.3.

**Comment by powercycle** [comment]
New release does not fix problem.  Same error occurs.  Please re-open.

**Comment by cnishina** [comment]
Yup this is not working. I was getting a version list without having the proxy and ignore ssl params passed. Will do a release tomorrow with the fix with #222

**Comment by cnishina** [comment]
@powercycle try again. 12.0.4. This has the actual fix. 😄

**Comment by powercycle** [comment]
unfortunately, same error.

**Comment by cnishina** [comment]
Are you sure you have the correct version? I would remove all the node_modules and reinstall.

**Comment by powercycle** [comment]
Working on that now.  How could I force it to use the local (not globally installed) version?

**Comment by powercycle** [comment]
Even after installing using npm -g install webdriver-manager@12.0.4, webdriver-manager version returns 12.0.2

**Comment by cnishina** [comment]
If you are running this from within a project, you'll end up selecting the project webdriver-manager version...and it will run the local version. I usually try to run global not within a project.

**Comment by powercycle** [comment]
Had to make changes to my path for some reason.  Seems to accept --proxy command line now.

**Comment by cnishina** [comment]
So it works? I can close this bug (again)?

**Comment by powercycle** [comment]
Yes, I have other problems now.... but not with webdriver-manager. :)

**Comment by cnishina** [comment]
Hooray! Closing. I am glad this is resolved. Sorry for your other problems.
