### ISSUE TITLE
Error: Failed to make Github request, rate limit reached.

### ISSUE THREAD

**Issue by christosptr** [angular/webdriver-manager#303]
I am running 
`webdriver-manager start` 
and I get the following error and webdriver fails to start 

(node:58736) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to make Github request, rate limit reached.
(node:58736) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js proces

Anyone else is seeing this issue?

**Comment by cnishina** [comment]
The start command should not make a request to GitHub. This was fixed in a later release. Please uninstall the current version of webdriver-manager and reinstall it. Let me know if that works.

**Comment by Niceplace** [comment]
I am experiencing this issue right now.

**Comment by christosptr** [comment]
Hi @cnishina Thanks for your responses. I did not see this issue for few days now.  Just so I can check and confirm in which release should this issue be fixed ?

**Comment by DenisVuyka** [comment]
Solution suggested by @p3x-robot in the link helped me as well.

**Comment by wachri** [comment]
It will not help if you like to run the tests in firefox... :unamused:

**Comment by virgile-hogman** [comment]
Still having the issue with gecko driver for firefox. The problem is this file is downloaded from api.github.com so i if you make too many requests at a given moment it fails. It's not a reliable solution :(

**Comment by cnishina** [comment]
This feature was resolved and released in the beta release of this and Protractor.

**Comment by virgile-hogman** [comment]
But i need the gecko driver for firefox, i don't want it to be disabled. Is that solved?

**Comment by donotello** [comment]
@cnishina, Could you please link here the PR with the fix?

Is this something similar to [Minishift's solution](https://github.com/minishift/minishift/blob/master/docs/source/troubleshooting/troubleshooting-getting-started.adoc#github-api-rate-limit-exceeded)?

**Comment by virgile-hogman** [comment]
Sorry but i'm still quite confused with the status of this issue.
Disabling gecko is definitely not an option at the moment since my tests are based on firefox.

> This feature was resolved and released in the beta release of this and Protractor.

Not really sure what the fix is about, i still have the problem with webdriver-manager 12.1.1 and Protractor 5.4.2 (which should be the last versions). Maybe you have some solution with a local cache, but in my case it doesn't work since this procedure can be run regularly from a Docker image therefore no cache is available. I'm conscious this is far from optimal but i have some other constraints that i can't change at the moment.

I checked a bit more in the existing tickets and as far as i understand, there are 3 ways to solve this:

- authenticated user with a github token. I'd like to avoid this solution, my build scripts are run on a server not related to a physical person.
- providing an alternative CDN. Not clear yet how it should be used. What should be stored and so on?
- providing a cache myself. It seems it's enough to cache the gecko-response.json which is the file read from api.github.com. The good news is that it's not necessary to cache the bigger geckodriver-{version}.tar.gz file. But to make it work the json file must be fresh enough, this can be done with `touch` as stated here (thanks @dandye !): https://github.com/angular/webdriver-manager/issues/270#issuecomment-376723889

Many people seems to have problems with this gecko driver so it should probably be better documented. For the moment i will stick to this last solution with my own cache but it's more of a temporary hack. So i'd be pleased to find a better solution in the future if possible :)

**Comment by mihaivarga** [comment]
When using protractor 6.0.0-beta (which has webdriver manager beta) webdriver-manager update works fine. However we run into a lot of other issues with the e2e tests. Not a good viable solution. We need a solution for protractor 5 first. 😢

**Comment by virgile-hogman** [comment]
@mihaivarga did you try the solution by caching yourself the `gecko-response.json` file? It works fine for me. But it's very hacky, on the long run it's not good since you'd need to update this file everytime a new driver is released.

@cnishina can you explain what the change in the beta version is about? I don't understand where the code of this beta can be seen nor how to install it. In any case removing gecko is not a solution, it's like saying "if the feature you need has some issues, then just disable it" :dancer: :unamused: :cry:

**Comment by mihaivarga** [comment]
> @mihaivarga did you try the solution by caching yourself the `gecko-response.json` file? It works fine for me. But it's very hacky, on the long run it's not good since you'd need to update this file everytime a new driver is released.

@virgile-hogman thanks. But no. I don't think it's a good solution as it seems like a breaking issue for webdriver-manager than an issue on consuming apps and it should be tackled by it. We will wait for a proper release on protractor 6. Right now the github api limit only gets hit by us rather rare.

**Comment by virgile-hogman** [comment]
@mihaivarga do you know what to expect in Protractor 6? I still have no clue what the supposed fix is about.

> Right now the github api limit only gets hit by us rather rare.

We have different needs, in my case this is used in a CI test framework running on servers on a daily basis. Something failing occasionally even rarely is not fine for us. This fix is clearly a very hacky patch but at least it always works as long as you don't need the updates.

**Comment by mihaivarga** [comment]
> @mihaivarga do you know what to expect in Protractor 6? I still have no clue what the supposed fix is about.
> 
> > Right now the github api limit only gets hit by us rather rare.
> 
> We have different needs, in my case this is used in a CI test framework running on servers on a daily basis. Something failing occasionally even rarely is not fine for us. This fix is clearly a very hacky patch but at least it always works as long as you don't need the updates.

@virgile-hogman haven't spent much time to investigate, gecko-driver issues seems to be fixed. I dropped it as it is beta and our working tests on 5+ where failing on 6 beta. I don't know if there are any plans on releasing a new 5+ with the latest `webdriver-manager` that might fix the issue.

**Comment by martinmthomas** [comment]
In my case, I think I made the mistake by installing both `protractor` and `webdriver-manager` globally. I uninstalled both the global packages and then installed just `protractor`. This resolved the "Rate limit" issue for me!

**Comment by virgile-hogman** [comment]
@martinmthomas this doesn't tell us anything about the versions you have been using. Reproducible issues don't usually disappear by magic.

**Comment by martinmthomas** [comment]
@virgile-hogman I do not know if it will reoccur whenever webdriver-manager is installed globally. But I was just sharing my experience. The versions are as following,
protractor: 5.4.2
webdriver-manager: 12.1.1
angular: 7.1.0
node: 8.11.2

**Comment by virgile-hogman** [comment]
Thanks for this. So you're still using Protractor 5. But are you able to put yourself in the context where your quote limit is reached? You need to run multiple request calls on api.github.com for that. Otherwise you won't really see the real problem.

From what i read here it's solved with Protractor 6. But I'm still really confused about it! The issue seems to come from webdriver manager, not Protractor. Am i wrong? May it's solved in Protractor 6 becomes it depends on a new version of webdriver manager that solves this?
Personally i'm with Angular 7.2.0, Protractor 5.4.2 which uses webdriver-manager ^12.0.6, resolving currently to 12.1.1.

Please can someone explain if and where this issue is supposedly fixed? @cnishina or anyone else who could clarify this.

**Comment by cnishina** [comment]
Fixed as of 13.0.0. There is a flag you should be able to use or set via environment variables. I think you should be able to get to the help menu with `webdriver-manager update --help` to find the flag. Start did not make any additional calls (previously fixed) and should only start the selenium standalone server.

Sorry it has taken a while to fix this one.

**Comment by malindapw** [comment]
@cnishina is this 13.0.0. Has it been released yet? still, the latest is 12.1.7 Thanks

**Comment by srishidev10** [comment]
webdriver-manager start --gecko saved me.
